include(FetchContent)
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/android/sdl-source/CMakeLists.txt")
    set(FETCHCONTENT_SOURCE_DIR_SDL2 "${CMAKE_CURRENT_SOURCE_DIR}/android/sdl-source")
endif()
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(SDL_SHARED ON CACHE BOOL "" FORCE)
set(SDL_STATIC OFF CACHE BOOL "" FORCE)
set(SDL_TEST OFF CACHE BOOL "" FORCE)
FetchContent_Declare(sdl2 GIT_REPOSITORY https://github.com/libsdl-org/SDL.git GIT_TAG release-2.32.10 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(sdl2)
set(BUILD_SHARED_LIBS ON)
set(SDL2TTF_VENDORED ON CACHE BOOL "" FORCE)
set(SDL2TTF_HARFBUZZ OFF CACHE BOOL "" FORCE)
set(SDL2TTF_SAMPLES OFF CACHE BOOL "" FORCE)
FetchContent_Declare(sdlttf GIT_REPOSITORY https://github.com/libsdl-org/SDL_ttf.git GIT_TAG release-2.24.0 GIT_SHALLOW TRUE GIT_SUBMODULES external/freetype)
FetchContent_MakeAvailable(sdlttf)
set(BUILD_SHARED_LIBS OFF)
set(PNG_SHARED OFF CACHE BOOL "" FORCE)
set(PNG_STATIC ON CACHE BOOL "" FORCE)
set(PNG_TESTS OFF CACHE BOOL "" FORCE)
set(PNG_TOOLS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(libpng GIT_REPOSITORY https://github.com/pnggroup/libpng.git GIT_TAG v1.6.50 GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(libpng)
add_library(PkgConfig::SDL2 ALIAS SDL2)
add_library(PkgConfig::SDL2_TTF ALIAS SDL2_ttf)
if(NOT TARGET PNG::PNG)
    add_library(PNG::PNG ALIAS png_static)
endif()
